name: Loyalty-Points-Market
main: io.github.sanakitty.loyaltypointsmarket.LoyaltyPointsMarket
version: 0.1
api-version: 1.13
author: SanaKitty
permissions:
   lpm.*:
      description: Gives access to all lpm commands.
      default: op
   lpm.admin:
      description: Allows the user to enter admin mode to check various info and data.
      default: op 
   lpm.check.other:
      description: Allows the user to check someone else's point count.
      default: op
   lpm.points.modify:
      description: Allows the user to modify someone's points.
      default: op
   lpm.shopkeeper.creative:
      description: Allows the user to create a creative shop.
      default: op
commands:
   lpm:
      description: Loyalty Points Market base command.
      usage: /<command>
   lpm request:
      description: Requests access and refresh tokens.
      usage: /<command> [authentication token]
      permission: lpm.request
      permission-message: This command can only be run by the console.
   lpm player add:
      description: Adds a player to the plugins' database on the server.
      usage: /<command> [Minecraft Username] [Twitch Username]
      permission: lpm.modifyplayer
      permission-message: You do not have the <permission> permission.
   lpm player edit:
      description: Edits the Twitch username associated with a specified player.
      usage: /<command> [Minecraft Username] [New Twitch Username]
      permission: lpm.modifyplayer
      permission-message: You do not have the <permission> permission.
   lpm player remove:
      description: Removes a player from the plugins' database on the server.
      usage: /<command> 
      permission: lpm.modifyplayer
      permission-message: You do not have the <permission> permission.
   lpm check:
      description: Displays a player's loyalty point count.
      usage: /<command> 
      permission: lpm.checkothers
      permission-message: You do not have the <permission> permission.
   lpm points add:
      description: Adds the specified amount of points to the given user.
      usage: /<command> 
      permission: lpm.points.modify
      permission-message: You do not have the <permission> permission.
   lpm points subtract:
      description: Subtracts the specified amount of points from the given user.
      usage: /<command> 
      permission: lpm.points.modify
      permission-message: You do not have the <permission> permission.
   lpm shop new:
      description: Gives the player the shop spawn item defined in the config, used to spawn a new Shopkeeper.
      usage: /<command> [-c] [profession]
      permission: lpm.shopkeeper.creative
      permission-message: You do not have the <permission> permission.