name: Loyalty-Points-Market
main: io.github.sanakitty.loyaltypointsmarket.LoyaltyPointsMarket
version: 0.1
api-version: 1.13
author: SanaKitty
permissions:
   lpm.*:
      description: Gives access to all lpm commands.
      default: op
   lpm.admin:
      description: Allows the user to enter admin mode to check various info and data.
      default: op 
   lpm.check.other:
      description: Allows the user to check someone else's point count.
      default: op
   lpm.points.modify:
      description: Allows the user to modify someone's points.
      default: op
   lpm.shopkeeper.creative:
      description: Allows the user to create a creative shop.
      default: op
commands:
   lpm:
      description: Requests access and refresh tokens.
      usage: /<command>
      permission: lpm.check
      permission-message: You don't have the <permission> permission.